// =============================================
// BAHÇEM — Bitki Veritabanı (300+ bitki)
// =============================================
const PLANTS_DB = [

  // ══════════════════════════════════════════
  // İÇ MEKAN / SALON BİTKİLERİ
  // ══════════════════════════════════════════
  { id:"monstera",       nameTr:"Monstera",              nameLat:"Monstera deliciosa",        emoji:"🌿", light:"Parlak dolaylı", waterDays:7,  care:"Büyük, delikli yaprakları ile tanınır. Toprağın üst kısmı kuruyunca sulayın. Yaprakları nemli bezle silin." },
  { id:"monstera_thai",  nameTr:"Thai Constellation",    nameLat:"Monstera deliciosa Thai",   emoji:"🌿", light:"Parlak dolaylı", waterDays:7,  care:"Nadide alacalı monstera çeşidi. Direkt güneşten kaçının, renk solabilir." },
  { id:"monstera_adans", nameTr:"Adanson Monsteras",     nameLat:"Monstera adansonii",        emoji:"🌿", light:"Parlak dolaylı", waterDays:7,  care:"Küçük delikli yapraklar, sarkma eğilimli. Nem seviyor." },
  { id:"pothos",         nameTr:"Pothos",                nameLat:"Epipremnum aureum",          emoji:"🍀", light:"Az ışık",       waterDays:7,  care:"En dayanıklı iç mekan bitkilerinden. Düşük ışıkta bile yaşar. Sarkan yapraklar suya işaret eder." },
  { id:"pothos_marble",  nameTr:"Mermer Pothos",         nameLat:"Epipremnum aureum Marble",  emoji:"🍀", light:"Parlak dolaylı", waterDays:7,  care:"Beyaz-yeşil alacalı yapraklar. Daha fazla ışıkla desen belirginleşir." },
  { id:"bariscicegi",    nameTr:"Barış Çiçeği",          nameLat:"Spathiphyllum wallisii",    emoji:"🌼", light:"Az ışık",       waterDays:5,  care:"Beyaz çiçekler açar. Gölgeyi sever. Toprak kuruyunca yapraklar sarkar, hemen sulayın." },
  { id:"benjamin",       nameTr:"Benjamin",              nameLat:"Ficus benjamina",           emoji:"🌳", light:"Parlak dolaylı", waterDays:7,  care:"Yer değiştirince yaprak döker. Kışın az sulayın. Stabil sıcaklık sever." },
  { id:"kemanYapragi",   nameTr:"Keman Yapraklı Ficus",  nameLat:"Ficus lyrata",              emoji:"🌳", light:"Parlak dolaylı", waterDays:7,  care:"Büyük koyu yeşil yapraklar. Kök bağlamayı sever, sık saksı değiştirmeyin." },
  { id:"pasacicegi",     nameTr:"Pasha Çiçeği",          nameLat:"Sansevieria trifasciata",   emoji:"🌿", light:"Her ışık",      waterDays:14, care:"En az bakım isteyen bitki. Kışın aylık bir sulama yeterli. Kök çürümesinden kaçının." },
  { id:"sanseveria_cyl", nameTr:"Silindir Pasha",        nameLat:"Sansevieria cylindrica",    emoji:"🌿", light:"Her ışık",      waterDays:14, care:"Silindirik yapraklar. Aşırı suya son derece hassas. Nadir sulama." },
  { id:"aloe",           nameTr:"Aloe Vera",             nameLat:"Aloe vera",                 emoji:"🌵", light:"Tam güneş",     waterDays:14, care:"Güneşi sever. Toprağın tamamen kurumasını bekleyin. Yanık ve cilt bakımında kullanılır." },
  { id:"orkide_phal",    nameTr:"Kelebek Orkide",        nameLat:"Phalaenopsis amabilis",     emoji:"🌸", light:"Parlak dolaylı", waterDays:7,  care:"Haftada bir bardak suyla sulayın. Çiçek düştükten sonra sap kesilir, tekrar çiçeklenebilir." },
  { id:"orkide_cym",     nameTr:"Cymbidium Orkide",      nameLat:"Cymbidium",                 emoji:"🌸", light:"Parlak dolaylı", waterDays:5,  care:"Serin kış sever. Çiçeklenme için 10°C gece sıcaklığı gerekir." },
  { id:"orkide_den",     nameTr:"Dendrobium Orkide",     nameLat:"Dendrobium",                emoji:"🌸", light:"Parlak dolaylı", waterDays:5,  care:"Çiçeklenme sonrası dinlenme dönemi gerekir, sulamayı azaltın." },
  { id:"kaktus",         nameTr:"Kaktüs",                nameLat:"Cactaceae",                 emoji:"🌵", light:"Tam güneş",     waterDays:21, care:"Bol güneş, az su. Kışın neredeyse hiç sulamayın. İyi drenaj şart." },
  { id:"sukulent",       nameTr:"Sukulent",              nameLat:"Succulent",                 emoji:"🪴", light:"Tam güneş",     waterDays:14, care:"Sulu toprakta çürür. Toprak tamamen kuruyunca bolca sulayın, sonra bekleyin." },
  { id:"devetabani",     nameTr:"Deve Tabanı (ZZ)",      nameLat:"Zamioculcas zamiifolia",    emoji:"🌿", light:"Az ışık",       waterDays:14, care:"Neredeyse bakımsız yaşar. Düşük ışık ve az su ile mükemmel. İdeal ofis bitkisi." },
  { id:"philodendron_h", nameTr:"Sarmaşık Filodendron",  nameLat:"Philodendron hederaceum",   emoji:"🍃", light:"Parlak dolaylı", waterDays:7,  care:"Sarkan formlar için raftan sarkıtın. Toprak hafif nemli kalmalı." },
  { id:"philodendron_b", nameTr:"Bölünmüş Yaprak",       nameLat:"Philodendron bipinnatifidum",emoji:"🍃",light:"Parlak dolaylı", waterDays:7,  care:"Büyük dilimli yapraklar. Geniş alan ister. Yüksek nem sever." },
  { id:"philodendron_p", nameTr:"Pembe Prenses",         nameLat:"Philodendron erubescens",   emoji:"🍃", light:"Parlak dolaylı", waterDays:7,  care:"Pembe-kırmızı tonları olan nadide çeşit. Dolaylı ışık renklerini korur." },
  { id:"calathea",       nameTr:"Calathea",              nameLat:"Calathea ornata",           emoji:"🌿", light:"Az ışık",       waterDays:5,  care:"Geceleri yapraklarını kapatır. Kireçsiz su ve yüksek nem ister." },
  { id:"calathea_med",   nameTr:"Tavuskuşu Bitkisi",     nameLat:"Calathea makoyana",         emoji:"🌿", light:"Az ışık",       waterDays:4,  care:"Tavuskuşu desenli yapraklar. Klorlu suya hassas, filtreli su kullanın." },
  { id:"calathea_zebr",  nameTr:"Zebra Bitkisi",         nameLat:"Calathea zebrina",          emoji:"🌿", light:"Az ışık",       waterDays:5,  care:"Şeritli yapraklar. Yüksek nem ve dolaylı ışık şart." },
  { id:"maranta",        nameTr:"Dua Bitkisi",           nameLat:"Maranta leuconeura",        emoji:"🌿", light:"Az ışık",       waterDays:4,  care:"Geceleri yaprakları yukarı katlanır. Kireçsiz su, yüksek nem." },
  { id:"dracaena",       nameTr:"Drasena",               nameLat:"Dracaena marginata",        emoji:"🌴", light:"Parlak dolaylı", waterDays:10, care:"Flor'ü kaldıramaz. Toprağın üstü kuruyunca sulayın. Uzun ömürlü." },
  { id:"dracaena_frag",  nameTr:"Mutluluk Bitkisi",      nameLat:"Dracaena fragrans",         emoji:"🌴", light:"Az ışık",       waterDays:10, care:"Düşük ışığa dayanır. Toprak iyice kuruyunca sulayın." },
  { id:"dracaena_song",  nameTr:"Song of India",         nameLat:"Dracaena reflexa",          emoji:"🌴", light:"Parlak dolaylı", waterDays:10, care:"Sarı kenarlı yapraklar. Aşırı sulamadan kaçının." },
  { id:"kupaciegi",      nameTr:"Küpeli Çiçeği",         nameLat:"Fuchsia hybrida",           emoji:"🌺", light:"Yarı gölge",    waterDays:3,  care:"Serin ve nemli ortam sever. Sarkan küpe çiçekleri çok dekoratif. Düzenli sulama şart." },
  { id:"begonva",        nameTr:"Begonya",               nameLat:"Begonia semperflorens",     emoji:"🌸", light:"Parlak dolaylı", waterDays:4,  care:"Çiçekli iç mekan bitkisi. Toprak nemli ama batmamalı." },
  { id:"begonva_rex",    nameTr:"Rex Begonya",           nameLat:"Begonia rex",               emoji:"🌸", light:"Parlak dolaylı", waterDays:5,  care:"Renkli yaprakları için yetiştirilir. Yaprakları ıslatmayın, çürür." },
  { id:"cyclamen",       nameTr:"Siklamen",              nameLat:"Cyclamen persicum",         emoji:"🌷", light:"Parlak dolaylı", waterDays:5,  care:"Serin sever (15-18°C). Alttan sulayın, çiçekleri ıslatmayın." },
  { id:"anthurium",      nameTr:"Antoryum",              nameLat:"Anthurium andraeanum",      emoji:"🌹", light:"Parlak dolaylı", waterDays:5,  care:"Parlak kırmızı spathaları var. Yüksek nem ve dolaylı ışık sever." },
  { id:"anthurium_cla",  nameTr:"Kristal Antoryum",      nameLat:"Anthurium crystallinum",    emoji:"🌿", light:"Parlak dolaylı", waterDays:5,  care:"Kadife dokulu büyük yapraklar. Yüksek nem şart, teraryumda iyi." },
  { id:"yucca",          nameTr:"Yukka",                 nameLat:"Yucca elephantipes",        emoji:"🌴", light:"Tam güneş",     waterDays:14, care:"Kuraklığa dayanıklı. Kışın ayda bir sulayın. Kök çürümesinden kaçının." },
  { id:"aglonema",       nameTr:"Aglonema",              nameLat:"Aglaonema commutatum",      emoji:"🌿", light:"Az ışık",       waterDays:7,  care:"Düşük ışığa dayanır. Soğuğu ve hava akımını sevmez." },
  { id:"aglonema_red",   nameTr:"Kırmızı Aglonema",     nameLat:"Aglaonema red",             emoji:"🌿", light:"Parlak dolaylı", waterDays:7,  care:"Kırmızı-pembe yapraklar. Daha fazla dolaylı ışıkla rengi canlı kalır." },
  { id:"areka",          nameTr:"Areka Palmiyesi",       nameLat:"Dypsis lutescens",          emoji:"🌴", light:"Parlak dolaylı", waterDays:5,  care:"Nem sever, kuru havada uçları kararır. Kireçsiz su kullanın." },
  { id:"rubber",         nameTr:"Kauçuk Ağacı",          nameLat:"Ficus elastica",            emoji:"🌳", light:"Parlak dolaylı", waterDays:7,  care:"Parlak, büyük yapraklar. Aylık yaprak silme yapın." },
  { id:"rubber_bur",     nameTr:"Bordo Kauçuk",          nameLat:"Ficus elastica Burgundy",   emoji:"🌳", light:"Parlak dolaylı", waterDays:7,  care:"Koyu bordo yapraklar. Daha fazla ışıkla renk derinleşir." },
  { id:"tradescantia",   nameTr:"Tradeskantia",          nameLat:"Tradescantia zebrina",      emoji:"🍃", light:"Parlak dolaylı", waterDays:5,  care:"Sarkan mor-yeşil yapraklar. Hızlı büyür, budamayı sever." },
  { id:"oxalis",         nameTr:"Yonca Çiçeği",          nameLat:"Oxalis triangularis",       emoji:"🍀", light:"Parlak dolaylı", waterDays:5,  care:"Mor üçgen yapraklar. Geceleri kapanır. Dinlenme dönemi yaşar." },
  { id:"asparagus_fern", nameTr:"Kuşkonmaz Eğreltisi",   nameLat:"Asparagus setaceus",        emoji:"🌿", light:"Parlak dolaylı", waterDays:4,  care:"İnce tüylü yapraklar. Yüksek nem sever, düzenli sulama gerekir." },
  { id:"alocasia",       nameTr:"Fil Kulağı",            nameLat:"Alocasia amazonica",        emoji:"🌿", light:"Parlak dolaylı", waterDays:5,  care:"Büyük damarlı yapraklar. Yüksek nem sever. Soğuğa hassas." },
  { id:"alocasia_zebr",  nameTr:"Zebra Fil Kulağı",      nameLat:"Alocasia zebrina",          emoji:"🌿", light:"Parlak dolaylı", waterDays:5,  care:"Zebra desenli saplar. Yüksek nem şart, kışın daha az sulayın." },
  { id:"alocasia_black", nameTr:"Siyah Kadife",          nameLat:"Alocasia reginula",         emoji:"🌿", light:"Parlak dolaylı", waterDays:5,  care:"Koyu, kadife dokulu yapraklar. Toprağın üstü kuruyunca sulayın." },
  { id:"dieffenbachia",  nameTr:"Difenbahya",            nameLat:"Dieffenbachia seguine",     emoji:"🌿", light:"Az ışık",       waterDays:7,  care:"Zehirli bitki, evcil hayvanlardan uzak tutun. Düşük ışıkta iyi." },
  { id:"croton",         nameTr:"Kroton",                nameLat:"Codiaeum variegatum",       emoji:"🍂", light:"Tam güneş",     waterDays:5,  care:"Renkli yapraklar için bol güneş şart. Yer değiştirince yaprak döker." },
  { id:"schefflera",     nameTr:"Şemsiye Bitkisi",       nameLat:"Schefflera arboricola",     emoji:"🌿", light:"Parlak dolaylı", waterDays:7,  care:"Şemsiye şeklinde yaprak kümeleri. Toprağın üstü kuruyunca sulayın." },
  { id:"bromeliaid",     nameTr:"Bromeliad",             nameLat:"Bromeliaceae",              emoji:"🌺", light:"Parlak dolaylı", waterDays:7,  care:"Merkez rozetine su doldurun. Toprağı hafif nemli tutun." },
  { id:"tillandsia",     nameTr:"Hava Bitkisi",          nameLat:"Tillandsia ionantha",       emoji:"🌿", light:"Parlak dolaylı", waterDays:3,  care:"Topraksız yaşar. Haftada 2-3 kez hafifçe püskürtün ya da suya daldırın." },
  { id:"strelitzia",     nameTr:"Cennet Kuşu",           nameLat:"Strelitzia reginae",        emoji:"🦜", light:"Tam güneş",     waterDays:7,  care:"Turuncu-mavi egzotik çiçekler. Bol güneş ve serin kış gerekir." },
  { id:"kaktus_yil",     nameTr:"Yıldız Kaktüsü",        nameLat:"Gymnocalycium mihanovichii",emoji:"🌵", light:"Az ışık",       waterDays:14, care:"İç mekana uygun nadir kaktüs. Aşılı forma sahip, 2 haftada bir az sulama." },
  { id:"adenium",        nameTr:"Çöl Gülü",              nameLat:"Adenium obesum",            emoji:"🌸", light:"Tam güneş",     waterDays:7,  care:"Kökü şişkin, su depolar. Kışın çok az sulayın. Egzotik çiçekler açar." },
  { id:"echeveria",      nameTr:"Echeveria",             nameLat:"Echeveria elegans",         emoji:"🌸", light:"Tam güneş",     waterDays:14, care:"Gül şeklindeki rozet yapıları. Fazla su tehlikeli. Saksı tabanı delikli olmalı." },
  { id:"echeveria_lau",  nameTr:"Mor Echeveria",         nameLat:"Echeveria laui",            emoji:"🌸", light:"Tam güneş",     waterDays:14, care:"Pudralı pembe-mor yapraklar. Yapraklara su değdirmeyin, leke bırakır." },
  { id:"aeonium",        nameTr:"Taşgülü",               nameLat:"Aeonium arboreum",          emoji:"🌸", light:"Tam güneş",     waterDays:14, care:"Kışın büyür, yazın dinlenir. Az su sever. Kış yağışıyla yetinir." },
  { id:"haworthia",      nameTr:"Havorthia",             nameLat:"Haworthia attenuata",       emoji:"🌵", light:"Az ışık",       waterDays:14, care:"İç mekanda yaşayabilen nadir sukulent. Düşük ışıkta bile sağlıklı kalır." },
  { id:"lithops",        nameTr:"Canlı Taş",             nameLat:"Lithops hookeri",           emoji:"🪨", light:"Tam güneş",     waterDays:21, care:"Taşa benzeyen sukulent. Ayda bir sulama yeterli. Kışın hiç sulamayın." },
  { id:"sedum",          nameTr:"Sedum",                 nameLat:"Sedum morganianum",         emoji:"🌿", light:"Tam güneş",     waterDays:14, care:"Sarkık damla yapraklar. Saksıdan sarkıtılır. Çok az su ister." },
  { id:"crassula",       nameTr:"Para Ağacı",            nameLat:"Crassula ovata",            emoji:"🌳", light:"Tam güneş",     waterDays:14, care:"Bonsai görünümlü sukulent. Kışın çiçek açar. Az su, bol güneş." },
  { id:"hoya",           nameTr:"Hoya",                  nameLat:"Hoya carnosa",              emoji:"🌸", light:"Parlak dolaylı", waterDays:10, care:"Balmumu görünümlü yapraklar. Çiçek kümeleri açar. Az su sever." },
  { id:"hoya_heart",     nameTr:"Kalp Yapraklı Hoya",    nameLat:"Hoya kerrii",               emoji:"💚", light:"Parlak dolaylı", waterDays:14, care:"Kalp şekilli yapraklar. Yavaş büyür, sabır ister. Az su." },
  { id:"peperomia",      nameTr:"Peperomya",             nameLat:"Peperomia obtusifolia",     emoji:"🌿", light:"Parlak dolaylı", waterDays:10, care:"Etli yapraklar. Aşırı sulamadan kaçının. İdeal başlangıç bitkisi." },
  { id:"peperomia_wm",   nameTr:"Karpuz Peperomya",      nameLat:"Peperomia argyreia",        emoji:"🍉", light:"Parlak dolaylı", waterDays:10, care:"Karpuz desenli yapraklar. Küçük boyutu ile masa bitkisi." },
  { id:"fittonia",       nameTr:"Fittonia",              nameLat:"Fittonia albivenis",        emoji:"🌿", light:"Az ışık",       waterDays:3,  care:"Damarlı yapraklar. Çok nem sever. Kuruyunca hemen solar, sulayın." },
  { id:"pilea",          nameTr:"Pilea",                 nameLat:"Pilea peperomioides",       emoji:"🌿", light:"Parlak dolaylı", waterDays:7,  care:"Yuvarlak yapraklar. Hızlı büyür, yavru verir. Kolay bakımlı." },
  { id:"arrowhead",      nameTr:"Ok Yapraklı Bitki",     nameLat:"Syngonium podophyllum",     emoji:"🍃", light:"Az ışık",       waterDays:5,  care:"Ok şekli yapraklar. Olgunlaşınca sarkmaya başlar. Az ışıkta iyi." },
  { id:"rubber_panda",   nameTr:"Panda Bitkisi",         nameLat:"Kalanchoe tomentosa",       emoji:"🐼", light:"Tam güneş",     waterDays:14, care:"Kadifemsi beyaz tüylü yapraklar. Çok az su. Güneşi sever." },
  { id:"nerve_plant",    nameTr:"Sinir Bitkisi",         nameLat:"Fittonia verschaffeltii",   emoji:"🌿", light:"Az ışık",       waterDays:3,  care:"Kırmızı damarlı yapraklar. Nem şart, teraryumda iyi yetişir." },
  { id:"cast_iron",      nameTr:"Dökme Demir Bitkisi",   nameLat:"Aspidistra elatior",        emoji:"🌿", light:"Az ışık",       waterDays:14, care:"Her koşulda yaşar. Gölge, soğuk, ihmal — sorun etmez." },
  { id:"ponytail",       nameTr:"At Kuyruğu Palmiyesi",  nameLat:"Beaucarnea recurvata",      emoji:"🌴", light:"Tam güneş",     waterDays:14, care:"Dipte şişen kök su depolar. Çok az su. Kışın hemen hemen sulamayın." },
  { id:"umbrella_tree",  nameTr:"Şemsiye Ağacı",         nameLat:"Schefflera actinophylla",   emoji:"🌳", light:"Parlak dolaylı", waterDays:7,  care:"Büyük parmaklı yaprak kümeleri. Hava akımından koruyun." },
  { id:"chinese_money",  nameTr:"Çin Para Bitkisi",      nameLat:"Pilea peperomioides",       emoji:"🪙", light:"Parlak dolaylı", waterDays:7,  care:"Yuvarlak koin gibi yapraklar. Kolayca yavru verir, arkadaşa hediye edin." },
  { id:"spider_plant",   nameTr:"Örümcek Bitkisi",       nameLat:"Chlorophytum comosum",      emoji:"🕷️", light:"Parlak dolaylı", waterDays:7,  care:"Beyaz çizgili yapraklar, sarkan yavrular oluşturur. Çok dayanıklı." },
  { id:"boston_fern",    nameTr:"Boston Eğreltisi",       nameLat:"Nephrolepis exaltata",      emoji:"🌿", light:"Parlak dolaylı", waterDays:3,  care:"Yüksek nem şart. Kuru havada günlük püskürtme yapın. Asılı saksıda güzel." },
  { id:"maidenhair",     nameTr:"Venus Saçı Eğreltisi",   nameLat:"Adiantum raddianum",        emoji:"🌿", light:"Parlak dolaylı", waterDays:3,  care:"Narin ince yapraklar. Çok nemli ortam ister, teraryumda ideal." },
  { id:"staghorn",       nameTr:"Geyik Boynuzu Eğreltisi",nameLat:"Platycerium bifurcatum",   emoji:"🦌", light:"Parlak dolaylı", waterDays:7,  care:"Duvara monte edilir. Haftada bir kez suya daldırarak sulayın." },
  { id:"heartleaf",      nameTr:"Kalp Yapraklı Filodendron",nameLat:"Philodendron cordatum",  emoji:"💚", light:"Az ışık",       waterDays:7,  care:"Kalp şekilli yapraklar. Sarkmayı sever. Düşük ışıkta bile büyür." },
  { id:"velvet_calathea",nameTr:"Kadife Calathea",        nameLat:"Calathea velvet",           emoji:"🌿", light:"Az ışık",       waterDays:5,  care:"Kadife dokulu yapraklar. Kireçsiz su, yüksek nem şart." },
  { id:"birds_nest",     nameTr:"Kuş Yuvası Eğreltisi",   nameLat:"Asplenium nidus",           emoji:"🪺", light:"Az ışık",       waterDays:5,  care:"Ortasına su dökmekten kaçının. Dolaylı ışık ve nem sever." },

  // ══════════════════════════════════════════
  // BALKON / BAHÇE ÇİÇEKLERİ
  // ══════════════════════════════════════════
  { id:"gul",            nameTr:"Gül",                   nameLat:"Rosa",                      emoji:"🌹", light:"Tam güneş",     waterDays:3,  care:"Günde en az 6 saat güneş. Hastalıklara yatkın, budama şart. Çiçek sonrası gübre verin." },
  { id:"gul_climbing",   nameTr:"Tırmanıcı Gül",         nameLat:"Rosa climbing",             emoji:"🌹", light:"Tam güneş",     waterDays:3,  care:"Duvar ve pergola kaplar. Yıllık sert budama ile daha fazla çiçek." },
  { id:"lavanta",        nameTr:"Lavanta",               nameLat:"Lavandula angustifolia",    emoji:"💜", light:"Tam güneş",     waterDays:10, care:"Kuraklığa dayanıklı. İyi drene edilmiş toprak. Çiçek açınca hasat edin." },
  { id:"lavanta_french", nameTr:"Fransız Lavantası",     nameLat:"Lavandula stoechas",        emoji:"💜", light:"Tam güneş",     waterDays:10, care:"Kulak şeklinde çiçekler. Daha sıcak iklim sever." },
  { id:"papatya",        nameTr:"Papatya",               nameLat:"Bellis perennis",           emoji:"🌼", light:"Tam güneş",     waterDays:4,  care:"Bol güneş ve düzenli sulama ile uzun süre çiçek açar." },
  { id:"lale",           nameTr:"Lale",                  nameLat:"Tulipa",                    emoji:"🌷", light:"Tam güneş",     waterDays:5,  care:"Soğan bitkisi. Sonbaharda ekilir, baharda çiçek açar. Yaz aylarında dinlenir." },
  { id:"lale_parrot",    nameTr:"Papağan Lalesi",        nameLat:"Tulipa parrot",             emoji:"🌷", light:"Tam güneş",     waterDays:5,  care:"Dalgalı renkli taçyapraklar. Ağır başlı, rüzgardan koruyun." },
  { id:"sunflower",      nameTr:"Ayçiçeği",              nameLat:"Helianthus annuus",         emoji:"🌻", light:"Tam güneş",     waterDays:4,  care:"Güneşe dönen yüzü ile tanınır. Derin sulama gerekir, sığ sulama zararlı." },
  { id:"begonvil",       nameTr:"Bougainvillea",         nameLat:"Bougainvillea glabra",      emoji:"🌺", light:"Tam güneş",     waterDays:5,  care:"Sıcak iklim bitkisi. Az su ile daha fazla çiçek açar. Dondan koruyun." },
  { id:"sardunya",       nameTr:"Sardunya",              nameLat:"Pelargonium hortorum",      emoji:"🌸", light:"Tam güneş",     waterDays:4,  care:"Balkon favorisi. Toprak kuruyunca sulayın. Kış aylarında içeri alın." },
  { id:"petunya",        nameTr:"Petunya",               nameLat:"Petunia hybrida",           emoji:"🌸", light:"Tam güneş",     waterDays:3,  care:"Hızlı büyür. Sürekli çiçekler için düzenli gübre. Yağmurdan sonra budayın." },
  { id:"gelincik",       nameTr:"Gelincik",              nameLat:"Papaver rhoeas",            emoji:"🌺", light:"Tam güneş",     waterDays:4,  care:"Kırmızı narin taçyapraklar. Kendiliğinden tohumlanır, her yıl gelir." },
  { id:"hanımeli",       nameTr:"Hanımeli",              nameLat:"Lonicera japonica",         emoji:"🌿", light:"Tam güneş",     waterDays:4,  care:"Tırmanıcı bitki. Güçlü koku. Çit ve duvar kaplamak için ideal." },
  { id:"yasemin",        nameTr:"Yasemin",               nameLat:"Jasminum officinale",       emoji:"🌼", light:"Tam güneş",     waterDays:4,  care:"Yoğun beyaz çiçek kokusu. Tırmanıcı. Yazın bol çiçek, kışın dinlenme." },
  { id:"glayol",         nameTr:"Glayol",                nameLat:"Gladiolus communis",        emoji:"🌷", light:"Tam güneş",     waterDays:4,  care:"Yumru bitkisi. Yazın çiçek açar, sonbaharda yumrular sökülebilir." },
  { id:"iris",           nameTr:"İris",                  nameLat:"Iris germanica",            emoji:"💜", light:"Tam güneş",     waterDays:7,  care:"Rizomlu bitki. Aşırı sulama çürümeye neden olur. 3 yılda bir bölün." },
  { id:"zerrin",         nameTr:"Zerrin",                nameLat:"Narcissus pseudonarcissus", emoji:"🌼", light:"Tam güneş",     waterDays:5,  care:"İlkbaharda açar. Soğan bitkisi, yazın dinlenir. Zehirlidir, dikkat." },
  { id:"hidrangea",      nameTr:"Ortanca",               nameLat:"Hydrangea macrophylla",     emoji:"💜", light:"Yarı gölge",    waterDays:3,  care:"Bol su sever. Toprak asitliğine göre renk değişir. Kışın budayın." },
  { id:"mimoza",         nameTr:"Mimoza",                nameLat:"Acacia dealbata",           emoji:"🌼", light:"Tam güneş",     waterDays:7,  care:"Kışın sarı tomurcuklar. Sıcak iklim sever. Hızlı büyür." },
  { id:"manolya",        nameTr:"Manolya",               nameLat:"Magnolia grandiflora",      emoji:"🌸", light:"Tam güneş",     waterDays:5,  care:"İlkbaharda açan devasa çiçekler. Yer değiştirmekten hoşlanmaz." },
  { id:"sakura",         nameTr:"Japon Kirazı",          nameLat:"Prunus serrulata",          emoji:"🌸", light:"Tam güneş",     waterDays:4,  care:"İlkbaharda pembe çiçek yağmuru. Sonbaharda budama." },
  { id:"japon_akcaagac", nameTr:"Japon Akçaağacı",       nameLat:"Acer palmatum",             emoji:"🍁", light:"Yarı gölge",    waterDays:4,  care:"Derin kırmızı yapraklar. Sert güneşten koruyun." },
  { id:"forsythia",      nameTr:"Altın Çan",             nameLat:"Forsythia intermedia",      emoji:"🌼", light:"Tam güneş",     waterDays:7,  care:"İlkbaharda yapraktan önce sarı çiçekler açar. Kışa dayanıklı." },
  { id:"buddleia",       nameTr:"Kelebek Çalısı",        nameLat:"Buddleja davidii",          emoji:"💜", light:"Tam güneş",     waterDays:7,  care:"Mor çiçek salkımları kelebekleri çeker. Kışa dayanıklı, kolay büyür." },
  { id:"abelia",         nameTr:"Abelia",                nameLat:"Abelia grandiflora",        emoji:"🌸", light:"Tam güneş",     waterDays:7,  care:"Yaz-sonbahar çiçeklenir. Kelebek ve arıları çeker. Kışa dayanıklı." },
  { id:"weigela",        nameTr:"Weigela",               nameLat:"Weigela florida",           emoji:"🌸", light:"Tam güneş",     waterDays:7,  care:"Bahar-yaz arası pembe-kırmızı çiçekler. Budamayı sever." },
  { id:"dahlia",         nameTr:"Yıldız Çiçeği",         nameLat:"Dahlia pinnata",            emoji:"🌸", light:"Tam güneş",     waterDays:4,  care:"Yumru bitkisi. Yazın bol çiçek. Kışa hassas, yumruları saklayın." },
  { id:"zinnia",         nameTr:"Zinnia",                nameLat:"Zinnia elegans",            emoji:"🌸", light:"Tam güneş",     waterDays:4,  care:"Renkli, uzun çiçek döngüsü. Hızlı büyür, tohumdan kolayca yetişir." },
  { id:"marigold",       nameTr:"Kadife Çiçeği",         nameLat:"Tagetes erecta",            emoji:"🟡", light:"Tam güneş",     waterDays:4,  care:"Turuncu-sarı çiçekler. Böcekleri uzak tutar. İdeal sınır bitkisi." },
  { id:"snapdragon",     nameTr:"Aslan Ağzı",            nameLat:"Antirrhinum majus",         emoji:"🌸", light:"Tam güneş",     waterDays:4,  care:"İlkbahar-yaz çiçeklenir. Kesme çiçek olarak kullanılır." },
  { id:"impatiens",      nameTr:"Sabırsız Gelin",        nameLat:"Impatiens walleriana",      emoji:"🌸", light:"Yarı gölge",    waterDays:3,  care:"Gölge seven çiçek. Çok renk seçeneği. Düzenli sulama şart." },
  { id:"pansies",        nameTr:"Hercai Menekşe",        nameLat:"Viola tricolor",            emoji:"💜", light:"Yarı gölge",    waterDays:3,  care:"Serin havayı sever. İlkbahar ve sonbahar da iyi büyür." },
  { id:"alyssum",        nameTr:"Alysum",                nameLat:"Lobularia maritima",        emoji:"🌸", light:"Tam güneş",     waterDays:4,  care:"Bal kokulu küçük beyaz çiçekler. Kaplama bitkisi olarak güzel." },
  { id:"stock",          nameTr:"Şebboy",                nameLat:"Matthiola incana",          emoji:"🌸", light:"Tam güneş",     waterDays:4,  care:"Yoğun kokulu çiçekler. Serin havada daha güzel büyür." },
  { id:"hollyhock",      nameTr:"Gülhatmi",              nameLat:"Alcea rosea",               emoji:"🌸", light:"Tam güneş",     waterDays:5,  care:"Uzun boylu, görkemli çiçekler. Duvar diplerine yakın ekin." },
  { id:"delphinium",     nameTr:"Hezaren",               nameLat:"Delphinium elatum",         emoji:"💜", light:"Tam güneş",     waterDays:4,  care:"Uzun mavi-mor çiçek başakları. Rüzgardan koruyun, destek gerekir." },
  { id:"cosmos",         nameTr:"Küçük Yıldız",          nameLat:"Cosmos bipinnatus",         emoji:"🌸", light:"Tam güneş",     waterDays:4,  care:"Narin görünümlü ama sağlam. Az bakımla bol çiçek açar." },
  { id:"verbena",        nameTr:"Mine Çiçeği",           nameLat:"Verbena bonariensis",       emoji:"💜", light:"Tam güneş",     waterDays:4,  care:"Uzun saplı mor çiçekler. Kelebekleri çeker. Az su ile büyür." },
  { id:"salvia_orn",     nameTr:"Süs Adaçayı",           nameLat:"Salvia splendens",          emoji:"🔴", light:"Tam güneş",     waterDays:4,  care:"Parlak kırmızı başaklar. Uzun çiçeklenme dönemi. Sıcağı sever." },
  { id:"foxglove",       nameTr:"Yüksük Çiçeği",         nameLat:"Digitalis purpurea",        emoji:"🌸", light:"Yarı gölge",    waterDays:4,  care:"Zehirli! Uzun çiçek başakları. İki yıllık. Gölgeye dayanır." },
  { id:"lupin",          nameTr:"Acı Bakla Çiçeği",      nameLat:"Lupinus polyphyllus",       emoji:"💜", light:"Tam güneş",     waterDays:5,  care:"Uzun, çok renkli çiçek başakları. Toprağa azot verir." },

  // ══════════════════════════════════════════
  // SEBZE VE MEYVE
  // ══════════════════════════════════════════
  { id:"domates",        nameTr:"Domates",               nameLat:"Solanum lycopersicum",      emoji:"🍅", light:"Tam güneş",     waterDays:2,  care:"Günde 8+ saat güneş. Düzenli ve derin sulama. Meyve bağlarken gübre." },
  { id:"domates_kiraz",  nameTr:"Kiraz Domates",         nameLat:"Solanum lycopersicum var.", emoji:"🍒", light:"Tam güneş",     waterDays:2,  care:"Normal domatese göre daha az bakım. Saksıda da yetişir." },
  { id:"biber",          nameTr:"Biber",                 nameLat:"Capsicum annuum",           emoji:"🌶️", light:"Tam güneş",     waterDays:3,  care:"Sıcak sever. Toprak nemli kalmalı ama batmamalı. Kırmızıya dönünce hasat." },
  { id:"patlican",       nameTr:"Patlıcan",              nameLat:"Solanum melongena",         emoji:"🍆", light:"Tam güneş",     waterDays:3,  care:"Sıcakta iyi büyür. Düzenli sulama ve gübre. Mor çiçekler açar." },
  { id:"salatalık",      nameTr:"Salatalık",             nameLat:"Cucumis sativus",           emoji:"🥒", light:"Tam güneş",     waterDays:2,  care:"Hızlı büyür. Tırmanması için destek verin. Günde bir sulama ideal." },
  { id:"kabak",          nameTr:"Kabak",                 nameLat:"Cucurbita pepo",            emoji:"🥬", light:"Tam güneş",     waterDays:3,  care:"Geniş yer ister. Büyük yapraklarda nem tutmayın. Bolca gübre." },
  { id:"marul",          nameTr:"Marul",                 nameLat:"Lactuca sativa",            emoji:"🥬", light:"Yarı gölge",    waterDays:2,  care:"Serin sever. Yazın sıcakta tohumlanır. Toprağı nemli tutun." },
  { id:"ispanak",        nameTr:"Ispanak",               nameLat:"Spinacia oleracea",         emoji:"🥬", light:"Yarı gölge",    waterDays:2,  care:"Serin sever, sıcakta çiçeklenir. İlkbahar ve sonbaharda ekin." },
  { id:"sogan",          nameTr:"Soğan",                 nameLat:"Allium cepa",               emoji:"🧅", light:"Tam güneş",     waterDays:5,  care:"İlkbaharda ekin. Yapraklar sarardığında hasat zamanı gelmiştir." },
  { id:"sarimsak",       nameTr:"Sarımsak",              nameLat:"Allium sativum",            emoji:"🧄", light:"Tam güneş",     waterDays:7,  care:"Sonbaharda dikilir, yazda hasat edilir. Toprak iyi drene olmalı." },
  { id:"cilek",          nameTr:"Çilek",                 nameLat:"Fragaria × ananassa",       emoji:"🍓", light:"Tam güneş",     waterDays:3,  care:"Günlük sulama gerekebilir. Kuşlardan koruyun. Her 3 yılda bir yenileyin." },
  { id:"ahududu",        nameTr:"Ahududu",               nameLat:"Rubus idaeus",              emoji:"🫐", light:"Tam güneş",     waterDays:4,  care:"Dikenli dalları destekle bağlayın. Çiçeklenme sonrası gübre." },
  { id:"boğurtlen",      nameTr:"Böğürtlen",             nameLat:"Rubus fruticosus",          emoji:"🫐", light:"Tam güneş",     waterDays:4,  care:"Hızlı yayılır, sınırlandırın. Güçlü dikenler, eldiven kullanın." },
  { id:"limon",          nameTr:"Limon",                 nameLat:"Citrus limon",              emoji:"🍋", light:"Tam güneş",     waterDays:5,  care:"Tüm yıl bol güneş. Kışın içeride tutun. Demir eksikliğine yatkın." },
  { id:"portakal",       nameTr:"Portakal",              nameLat:"Citrus sinensis",           emoji:"🍊", light:"Tam güneş",     waterDays:5,  care:"Sıcak iklim bitkisi. Tuz ve klordan uzak tutun." },
  { id:"mandalina",      nameTr:"Mandalina",             nameLat:"Citrus reticulata",         emoji:"🍊", light:"Tam güneş",     waterDays:5,  care:"Saksıda yetişmeye uygun narenciye. Kışın serin ama donmasın." },
  { id:"zeytin",         nameTr:"Zeytin",                nameLat:"Olea europaea",             emoji:"🫒", light:"Tam güneş",     waterDays:10, care:"Kuraklığa dayanıklı. Derin ve nadir sulama. Yüzyıllarca yaşar." },
  { id:"nar",            nameTr:"Nar",                   nameLat:"Punica granatum",           emoji:"🍎", light:"Tam güneş",     waterDays:7,  care:"Sıcak ve kuraklığa dayanıklı. Kışın düşük suya geçin." },
  { id:"incir",          nameTr:"İncir",                 nameLat:"Ficus carica",              emoji:"🍈", light:"Tam güneş",     waterDays:7,  care:"Hızlı büyür. Meyveli dönemde bol su. Kışın budama yapın." },
  { id:"visne",          nameTr:"Vişne",                 nameLat:"Prunus cerasus",            emoji:"🍒", light:"Tam güneş",     waterDays:5,  care:"Soğuklama ihtiyacı var. İlkbaharda çiçek, yazda meyve." },
  { id:"elma",           nameTr:"Elma",                  nameLat:"Malus domestica",           emoji:"🍎", light:"Tam güneş",     waterDays:7,  care:"Tozlaşma için 2 çeşit ekin. Kışın budama şart." },
  { id:"armut",          nameTr:"Armut",                 nameLat:"Pyrus communis",            emoji:"🍐", light:"Tam güneş",     waterDays:7,  care:"Elmaya benzer bakım. Ateş yanıklığına dikkat edin." },
  { id:"kayisi",         nameTr:"Kayısı",                nameLat:"Prunus armeniaca",          emoji:"🍑", light:"Tam güneş",     waterDays:7,  care:"Erken çiçeklenir, don riskine dikkat. Sıcak yazları sever." },
  { id:"musmula",        nameTr:"Muşmula",               nameLat:"Eriobotrya japonica",       emoji:"🍊", light:"Tam güneş",     waterDays:7,  care:"Kışın çiçek açar. Hafif don tolere eder. Kışın meyve verir." },
  { id:"avokado",        nameTr:"Avokado",               nameLat:"Persea americana",          emoji:"🥑", light:"Tam güneş",     waterDays:5,  care:"Tohumdan yetiştirebilirsiniz. Meyve vermesi için yıllar gerekir." },
  { id:"kivi",           nameTr:"Kivi",                  nameLat:"Actinidia deliciosa",       emoji:"🥝", light:"Tam güneş",     waterDays:5,  care:"Tırmanıcı. Erkek ve dişi bitki gerekir. Güçlü destek lazım." },
  { id:"uzum",           nameTr:"Üzüm",                  nameLat:"Vitis vinifera",            emoji:"🍇", light:"Tam güneş",     waterDays:7,  care:"Kışın sert budama şart. Hastalıklara karşı ilaçlama gerekebilir." },
  { id:"bezelye",        nameTr:"Bezelye",               nameLat:"Pisum sativum",             emoji:"🫛", light:"Tam güneş",     waterDays:3,  care:"Serin sever. Tırmanması için destek gerekir. Erkenci ekin." },
  { id:"fasulye",        nameTr:"Fasulye",               nameLat:"Phaseolus vulgaris",        emoji:"🫘", light:"Tam güneş",     waterDays:3,  care:"Sıcak sever. Düzenli hasatla daha fazla meyve. Destek olması iyi." },
  { id:"domates_salk",   nameTr:"Salkım Domates",        nameLat:"Solanum lycopersicum corymb",emoji:"🍅",light:"Tam güneş",     waterDays:2,  care:"Uzun salkımlarla bol meyve. Destek ve budama önemli." },
  { id:"brokkoli",       nameTr:"Brokoli",               nameLat:"Brassica oleracea italica", emoji:"🥦", light:"Tam güneş",     waterDays:3,  care:"Serin sever. Baş oluşunca tüm bitki hasat edilir." },
  { id:"karnabahar",     nameTr:"Karnabahar",            nameLat:"Brassica oleracea botrytis",emoji:"🌸", light:"Tam güneş",     waterDays:3,  care:"Brokoli gibi bakım. Beyaz kalması için yapraklarla örtün." },
  { id:"kereviz",        nameTr:"Kereviz",               nameLat:"Apium graveolens",          emoji:"🥬", light:"Yarı gölge",    waterDays:2,  care:"Bol su sever. Uzun yetişme süresi. Hem kökü hem yaprağı yenir." },
  { id:"havuc",          nameTr:"Havuç",                 nameLat:"Daucus carota",             emoji:"🥕", light:"Tam güneş",     waterDays:3,  care:"Derin, gevşek toprak gerekir. Taşlık veya çakıllı toprak dönük büyütür." },
  { id:"turp",           nameTr:"Turp",                  nameLat:"Raphanus sativus",          emoji:"🌶️", light:"Tam güneş",     waterDays:2,  care:"Hızlı büyür, 3-4 haftada hasat. Serin havada daha iyi." },
  { id:"patlican_b",     nameTr:"Beyaz Patlıcan",        nameLat:"Solanum melongena alba",    emoji:"⚪", light:"Tam güneş",     waterDays:3,  care:"Mor patlıcana benzer bakım. Daha az acı. Saksıda da yetişir." },
  { id:"tatli_patates",  nameTr:"Tatlı Patates",         nameLat:"Ipomoea batatas",           emoji:"🍠", light:"Tam güneş",     waterDays:4,  care:"Sıcak iklim sever. Yayılıcı sarmaşık formu dekoratif." },
  { id:"misir",          nameTr:"Mısır",                 nameLat:"Zea mays",                  emoji:"🌽", light:"Tam güneş",     waterDays:3,  care:"Rüzgar ile tozlaşır, blok halinde ekin. Bol gübre ister." },

  // ══════════════════════════════════════════
  // TIBBİ / ŞİFALI BİTKİLER
  // ══════════════════════════════════════════
  { id:"fesleğen",       nameTr:"Fesleğen",              nameLat:"Ocimum basilicum",          emoji:"🌱", light:"Tam güneş",     waterDays:2,  care:"Sıcaklık ve güneşe ihtiyaç duyar. Çiçekleri koparın, yaprak vermeye devam etsin." },
  { id:"nane",           nameTr:"Nane",                  nameLat:"Mentha spicata",            emoji:"🍃", light:"Yarı gölge",    waterDays:3,  care:"Hızlı yayılır, saksıda tutun. Düzenli sulama. Çiçeklenmeden önce hasat." },
  { id:"biberiye",       nameTr:"Biberiye",              nameLat:"Salvia rosmarinus",         emoji:"🌿", light:"Tam güneş",     waterDays:7,  care:"Akdeniz bitkisi. Az su sever. İyi drene edilmiş toprak. Kışa dayanıklı." },
  { id:"kekik",          nameTr:"Kekik",                 nameLat:"Thymus vulgaris",           emoji:"🌿", light:"Tam güneş",     waterDays:7,  care:"Kuraklığa dayanıklı. Çiçeklenmeden önce hasat. Çok yıllık." },
  { id:"adacayi",        nameTr:"Adaçayı",               nameLat:"Salvia officinalis",        emoji:"🌿", light:"Tam güneş",     waterDays:7,  care:"Az su ister. Baharda budayın. Hem dekoratif hem şifalı." },
  { id:"dereotu",        nameTr:"Dereotu",               nameLat:"Anethum graveolens",        emoji:"🌿", light:"Tam güneş",     waterDays:3,  care:"Hızlı büyür. Diğer bitkilerle yakın ekmekten kaçının." },
  { id:"maydanoz",       nameTr:"Maydanoz",              nameLat:"Petroselinum crispum",      emoji:"🌿", light:"Yarı gölge",    waterDays:3,  care:"Nemli toprak sever. Tohumdan yavaş çimlenir. İki yıllık." },
  { id:"kişniş",         nameTr:"Kişniş",                nameLat:"Coriandrum sativum",        emoji:"🌿", light:"Tam güneş",     waterDays:3,  care:"Serin havada daha iyi büyür. Sıcakta hızlı çiçeklenir." },
  { id:"tarhun",         nameTr:"Tarhun",                nameLat:"Artemisia dracunculus",     emoji:"🌿", light:"Tam güneş",     waterDays:5,  care:"Az su ister. Yaz bitkisi. Çok yıllık. Çiçeklenmeden önce hasat." },
  { id:"melisa",         nameTr:"Melisa",                nameLat:"Melissa officinalis",       emoji:"🍃", light:"Yarı gölge",    waterDays:4,  care:"Limon kokulu. Strese karşı yatıştırıcı çay yapılır. Hızlı yayılır." },
  { id:"kediotu",        nameTr:"Kedi Otu",              nameLat:"Valeriana officinalis",     emoji:"🌸", light:"Yarı gölge",    waterDays:4,  care:"Uyku sorunu için şifalı. Kedileri çeker. Nemli toprak sever." },
  { id:"kantaron",       nameTr:"Kantaron",              nameLat:"Hypericum perforatum",      emoji:"🌼", light:"Tam güneş",     waterDays:5,  care:"Sarı çiçekler. Antidepresan etkili şifalı bitki. Kuru toprağı sever." },
  { id:"ekinezya",       nameTr:"Ekinezya",              nameLat:"Echinacea purpurea",        emoji:"🌸", light:"Tam güneş",     waterDays:5,  care:"Bağışıklık güçlendirici. Pembe çiçekler. Kelebekleri çeker." },
  { id:"papatya_adi",    nameTr:"Alman Papatyası",       nameLat:"Matricaria chamomilla",     emoji:"🌼", light:"Tam güneş",     waterDays:4,  care:"Çay için hasat edin. Kendi kendine tohumlanır, her yıl gelir." },
  { id:"rezene",         nameTr:"Rezene",                nameLat:"Foeniculum vulgare",        emoji:"🌿", light:"Tam güneş",     waterDays:5,  care:"Anason benzeri koku. Hem tohum hem yaprak kullanılır. Uzun boylu." },
  { id:"kimyon",         nameTr:"Kimyon",                nameLat:"Cuminum cyminum",           emoji:"🌿", light:"Tam güneş",     waterDays:5,  care:"Sıcak ve kuru iklim sever. Tohumlar olgunlaşınca hasat edin." },
  { id:"fesleğen_kutsal",nameTr:"Kutsal Fesleğen",       nameLat:"Ocimum tenuiflorum",        emoji:"🌱", light:"Tam güneş",     waterDays:2,  care:"Tulsi olarak da bilinir. Stres azaltıcı. Çiçeklenmeden hasat." },
  { id:"lavanta_drog",   nameTr:"Dar Yapraklı Lavanta",  nameLat:"Lavandula angustifolia",    emoji:"💜", light:"Tam güneş",     waterDays:10, care:"Uçucu yağı çok değerli. Kurutulup yastık içine konabilir." },
  { id:"sardunya_kok",   nameTr:"Kokulu Sardunya",       nameLat:"Pelargonium graveolens",    emoji:"🌸", light:"Tam güneş",     waterDays:5,  care:"Gül kokulu yapraklar. Böcek kovucu. Yemek ve sabunda kullanılır." },
  { id:"civanpercemi",   nameTr:"Civanperçemi",          nameLat:"Achillea millefolium",      emoji:"🌼", light:"Tam güneş",     waterDays:7,  care:"Yara iyileştirici. Beyaz-sarı çiçekler. Kuraklığa dayanıklı." },
  { id:"biberye",        nameTr:"Pelin Otu",             nameLat:"Artemisia absinthium",      emoji:"🌿", light:"Tam güneş",     waterDays:10, care:"Gümüş yapraklar. Böcek kovucu. Çok güçlü, tıbbi kullanım dikkat ister." },
  { id:"mürver",         nameTr:"Mürver",                nameLat:"Sambucus nigra",            emoji:"🌸", light:"Tam güneş",     waterDays:5,  care:"Beyaz çiçekler ve siyah meyveler şifalı. Şerbet ve reçel yapılır." },
  { id:"limon_balm",     nameTr:"Limon Otu",             nameLat:"Melissa officinalis",       emoji:"🍋", light:"Yarı gölge",    waterDays:4,  care:"Limon kokulu. Çay yapılır. Nane gibi hızlı yayılır, saksıda tutun." },
  { id:"oregano",        nameTr:"Kekik Otu",             nameLat:"Origanum vulgare",          emoji:"🌿", light:"Tam güneş",     waterDays:7,  care:"Kuru ve güneşli ortam sever. Pizza ve makarna için mükemmel." },
  { id:"hibiskus",       nameTr:"Hibiskus",              nameLat:"Hibiscus rosa-sinensis",    emoji:"🌺", light:"Tam güneş",     waterDays:4,  care:"Sıcak sever. Büyük renkli çiçekler. Çay olarak da tüketilir." },

  // ══════════════════════════════════════════
  // TROPİKAL VE EGZOTİK
  // ══════════════════════════════════════════
  { id:"bonsai",         nameTr:"Bonsai",                nameLat:"Pinus thunbergii",          emoji:"🌲", light:"Tam güneş",     waterDays:2,  care:"Toprak asla tamamen kurumamalı. Yılda bir kez budama ve şekillendirme." },
  { id:"bambu",          nameTr:"Bambu",                 nameLat:"Phyllostachys aurea",       emoji:"🎋", light:"Tam güneş",     waterDays:3,  care:"Hızlı büyür. Geniş kap ister. Kök sınırlayıcı kullanın." },
  { id:"bambu_sarklı",   nameTr:"Şanslı Bambu",          nameLat:"Dracaena sanderiana",       emoji:"🎋", light:"Az ışık",       waterDays:7,  care:"Gerçek bambu değil. Suda da yaşar. Feng shui bitkisi." },
  { id:"carnivorPlant",  nameTr:"Sinekkapan",            nameLat:"Dionaea muscipula",         emoji:"🌿", light:"Tam güneş",     waterDays:3,  care:"Yalnızca damıtılmış su. Gübre vermeyin. Doğrudan güneş şart." },
  { id:"sarracenia",     nameTr:"Sürahi Bitkisi",        nameLat:"Sarracenia purpurea",       emoji:"🪣", light:"Tam güneş",     waterDays:3,  care:"Et yiyen bitki. Bataklık toprağı ve saf su gerekir." },
  { id:"nepenthes",      nameTr:"Köpek Dişi",            nameLat:"Nepenthes",                 emoji:"🪣", light:"Parlak dolaylı", waterDays:4,  care:"Tropikal et yiyen. Asılı sürahi yapraklar. Yüksek nem şart." },
  { id:"bromeliaid_neo", nameTr:"Neoregelia",            nameLat:"Neoregelia carolinae",      emoji:"🌺", light:"Parlak dolaylı", waterDays:7,  care:"Merkez rozete su doldurun. Çiçek öncesi ortası kızarır." },
  { id:"heliconia",      nameTr:"Istinya Bitkisi",       nameLat:"Heliconia rostrata",        emoji:"🌺", light:"Tam güneş",     waterDays:4,  care:"Egzotik sarkan çiçekler. Tropikal, sıcak ve nemli ortam ister." },
  { id:"ginger_plant",   nameTr:"Süs Zencefileği",       nameLat:"Alpinia zerumbet",          emoji:"🌸", light:"Yarı gölge",    waterDays:4,  care:"Yüksek nem. Egzotik çiçekler. Kök sapları parfümde kullanılır." },
  { id:"banana_plant",   nameTr:"Süs Muzu",              nameLat:"Musa ornata",               emoji:"🍌", light:"Tam güneş",     waterDays:4,  care:"Büyük yapraklar. Hızlı büyür. Rüzgardan koruyun, yapraklar yırtılır." },
  { id:"bird_palm",      nameTr:"Sabanal Palmiyesi",     nameLat:"Livistona chinensis",       emoji:"🌴", light:"Parlak dolaylı", waterDays:7,  care:"Yelpaze şeklinde yapraklar. Nemli toprak sever." },
  { id:"traveler_palm",  nameTr:"Yelpaze Palmiyesi",     nameLat:"Ravenala madagascariensis", emoji:"🌴", light:"Tam güneş",     waterDays:5,  care:"Görkemli yelpaze formu. Çok büyür, geniş alan lazım." },
  { id:"plumeria",       nameTr:"Plumeria",              nameLat:"Plumeria rubra",            emoji:"🌸", light:"Tam güneş",     waterDays:7,  care:"Hawaii çiçeği. Kışın yapraksız kalır. Kokusu çok hoş." },
  { id:"anthurium_cr",   nameTr:"Antoryum Kristal",      nameLat:"Anthurium crystallinum",    emoji:"🌿", light:"Parlak dolaylı", waterDays:5,  care:"Kadife büyük yapraklar. Koleksiyonerlerin favorisi." },
  { id:"colocasia",      nameTr:"Fil Kulağı Taro",       nameLat:"Colocasia esculenta",       emoji:"🌿", light:"Yarı gölge",    waterDays:3,  care:"Çok büyük yapraklar. Nemli-bataklık ortamı sever." },
  { id:"caladium",       nameTr:"Kaladyum",              nameLat:"Caladium bicolor",          emoji:"🌿", light:"Parlak dolaylı", waterDays:5,  care:"Renkli kalp şekli yapraklar. Kışın soğan dinlenmeye çekilir." },
  { id:"canna",          nameTr:"Hint Lalesi",           nameLat:"Canna indica",              emoji:"🌺", light:"Tam güneş",     waterDays:4,  care:"Büyük yapraklar, egzotik çiçekler. Kışın yumrular kazınır." },
  { id:"passionfruit",   nameTr:"Çarkıfelek",            nameLat:"Passiflora caerulea",       emoji:"🌸", light:"Tam güneş",     waterDays:4,  care:"Sarmaşık. Yuvarlak mavi-beyaz çiçekler. Çit kaplama için güzel." },
  { id:"bougainvillea_w",nameTr:"Beyaz Bugenvil",        nameLat:"Bougainvillea white",       emoji:"🤍", light:"Tam güneş",     waterDays:5,  care:"Beyaz brakte yapraklar. Pembe çeşitle aynı bakım." },
  { id:"ixora",          nameTr:"İksora",                nameLat:"Ixora coccinea",            emoji:"🌺", light:"Tam güneş",     waterDays:4,  care:"Küçük kırmızı çiçek kümeleri. Asit toprak sever." },
  { id:"plumbago",       nameTr:"Plumbago",              nameLat:"Plumbago auriculata",       emoji:"💙", light:"Tam güneş",     waterDays:5,  care:"Mavi çiçek. Çit bitkisi olarak uygun. Yazın çok çiçek açar." },

  // ══════════════════════════════════════════
  // AĞAÇLAR VE ÇALILAR
  // ══════════════════════════════════════════
  { id:"findik",         nameTr:"Fındık",                nameLat:"Corylus avellana",          emoji:"🌰", light:"Tam güneş",     waterDays:7,  care:"Kışa dayanıklı. Nemli toprak sever. Meyveler eylülde olgunlaşır." },
  { id:"ceviz",          nameTr:"Ceviz",                 nameLat:"Juglans regia",             emoji:"🌰", light:"Tam güneş",     waterDays:7,  care:"Derin kök salar. Geniş alan ister. Kimyasal madde salgılar, uzakta ekin." },
  { id:"defne",          nameTr:"Defne",                 nameLat:"Laurus nobilis",            emoji:"🌿", light:"Tam güneş",     waterDays:7,  care:"Akdeniz bitkisi. Yapraklar baharat. Yavaş büyür." },
  { id:"sedir",          nameTr:"Sedir",                 nameLat:"Cedrus libani",             emoji:"🌲", light:"Tam güneş",     waterDays:10, care:"Uzun ömürlü. İlk yıllarda düzenli sulama. Kuraklığa dayanır." },
  { id:"servi",          nameTr:"Servi",                 nameLat:"Cupressus sempervirens",    emoji:"🌲", light:"Tam güneş",     waterDays:10, care:"Yüksek, dar form. Kışa dayanıklı. Rüzgar kıranı olarak kullanılır." },
  { id:"cınar",          nameTr:"Çınar",                 nameLat:"Platanus orientalis",       emoji:"🌳", light:"Tam güneş",     waterDays:7,  care:"Çok büyür. Geniş alan şart. Gölge sağlar. Uzun ömürlü." },
  { id:"kızılcam",       nameTr:"Kızılçam",              nameLat:"Pinus brutia",              emoji:"🌲", light:"Tam güneş",     waterDays:14, care:"Kuraklığa dayanıklı Akdeniz çamı. Hızlı büyür." },
  { id:"kayın",          nameTr:"Kayın",                 nameLat:"Fagus sylvatica",           emoji:"🌳", light:"Yarı gölge",    waterDays:7,  care:"Geniş yapraklı. Sonbaharda renk şöleni yaşatır." },
  { id:"dişbudak",       nameTr:"Dişbudak",              nameLat:"Fraxinus excelsior",        emoji:"🌳", light:"Tam güneş",     waterDays:7,  care:"Hızlı büyür. Nem sever. Geniş gölge sağlar." },
  { id:"huş",            nameTr:"Huş Ağacı",             nameLat:"Betula pendula",            emoji:"🌳", light:"Tam güneş",     waterDays:7,  care:"Beyaz kabuk. Serin iklim sever. Bataklık kenarlarında iyi büyür." },
  { id:"ardic",          nameTr:"Ardıç",                 nameLat:"Juniperus communis",        emoji:"🌲", light:"Tam güneş",     waterDays:14, care:"Kuraklığa dayanıklı. Meyveleri baharat olarak kullanılır." },
  { id:"karaagac",       nameTr:"Karaağaç",              nameLat:"Ulmus minor",               emoji:"🌳", light:"Tam güneş",     waterDays:7,  care:"Hızlı büyür, geniş gölge sağlar. Karaağaç hastalığına dikkat." },
  { id:"leylak",         nameTr:"Leylak",                nameLat:"Syringa vulgaris",          emoji:"💜", light:"Tam güneş",     waterDays:7,  care:"Yoğun kokulu bahar çiçeği. Kışa dayanıklı. Çiçek sonrası budayın." },
  { id:"kina_cicek",     nameTr:"Kına Çiçeği",           nameLat:"Lawsonia inermis",          emoji:"🌸", light:"Tam güneş",     waterDays:5,  care:"Tropikal çalı. Yaprakları kına boyası verir. Sıcak sever." },
  { id:"akasya",         nameTr:"Akasya",                nameLat:"Robinia pseudoacacia",      emoji:"🌳", light:"Tam güneş",     waterDays:10, care:"Hızlı büyür, kuraklığa dayanıklı. Koku güzel ama işgalci olabilir." },
  { id:"muhallebici",    nameTr:"Muhallebi Çiçeği",      nameLat:"Prunus laurocerasus",       emoji:"🌿", light:"Yarı gölge",    waterDays:7,  care:"Parlak yapraklar. Çit bitkisi olarak ideal. Kışa dayanıklı." },
  { id:"cotoneaster",    nameTr:"Dölek",                 nameLat:"Cotoneaster horizontalis",  emoji:"🔴", light:"Tam güneş",     waterDays:7,  care:"Yatay yayılan form. Kış meyvelerini kuşlar yer. Kışa dayanıklı." },
  { id:"pyracantha",     nameTr:"Ateş Dikeni",           nameLat:"Pyracantha coccinea",       emoji:"🔴", light:"Tam güneş",     waterDays:7,  care:"Kışın turuncu meyveler. Dikenli, çit bitkisi olarak mükemmel." },
  { id:"vitex",          nameTr:"Hayıt",                 nameLat:"Vitex agnus-castus",        emoji:"💜", light:"Tam güneş",     waterDays:7,  care:"Kuraklığa dayanıklı çalı. Lavantaya benzer mor çiçekler." },
  { id:"tamarix",        nameTr:"Ilgın",                 nameLat:"Tamarix gallica",           emoji:"🌸", light:"Tam güneş",     waterDays:10, care:"Tuzlu ve kurak toprağa dayanır. Sahil bitkisi." },

  // ══════════════════════════════════════════
  // SU BİTKİLERİ
  // ══════════════════════════════════════════
  { id:"nilufar",        nameTr:"Nilüfer",               nameLat:"Nymphaea alba",             emoji:"🪷", light:"Tam güneş",     waterDays:1,  care:"Su bitkisi. Havuzda yaşar. Derin güneşe ihtiyaç var. Soğuk kışlarda dipte kalar." },
  { id:"lotus",          nameTr:"Lotus",                 nameLat:"Nelumbo nucifera",          emoji:"🪷", light:"Tam güneş",     waterDays:1,  care:"Nilüfer ile akraba ama daha büyük. Derin su. Büyük görkemli çiçekler." },
  { id:"papirus",        nameTr:"Papirüs",               nameLat:"Cyperus papyrus",           emoji:"🌾", light:"Tam güneş",     waterDays:1,  care:"Sürekli su içinde yaşar. Kışın içeride tutun. Egzotik görünüm." },
  { id:"su_sidagi",      nameTr:"Su Sıdağı",             nameLat:"Iris pseudacorus",          emoji:"💛", light:"Tam güneş",     waterDays:1,  care:"Su kenarı bitkisi. Sarı çiçekler. Sığ sularda yetişir." },
  { id:"su_nanesi",      nameTr:"Su Nanesi",             nameLat:"Mentha aquatica",           emoji:"🍃", light:"Yarı gölge",    waterDays:1,  care:"Suda veya çok nemli toprakta büyür. Naneye benzer koku." },
  { id:"typha",          nameTr:"Kamış",                 nameLat:"Typha latifolia",           emoji:"🌾", light:"Tam güneş",     waterDays:1,  care:"Gölet kenarı. Sigar şeklinde meyveler. Hızlı yayılır, sınırlayın." },
  { id:"horsetail",      nameTr:"At Kuyruğu Otu",        nameLat:"Equisetum hyemale",         emoji:"🌾", light:"Yarı gölge",    waterDays:2,  care:"Boğumlu bambuya benzer yapı. Nem sever. Dekoratif kap bitkisi." },
  { id:"water_hyacinth", nameTr:"Su Sümbülü",            nameLat:"Eichhornia crassipes",      emoji:"💜", light:"Tam güneş",     waterDays:1,  care:"Suda yüzen bitki. Hızlı çoğalır. Havuzu temizler." },
  { id:"water_lettuce",  nameTr:"Su Marulu",             nameLat:"Pistia stratiotes",         emoji:"🌿", light:"Tam güneş",     waterDays:1,  care:"Suda yüzer. Balık havuzu için gölge sağlar. Tropikal." },
  { id:"cyperus",        nameTr:"Cyperus",               nameLat:"Cyperus alternifolius",     emoji:"🌾", light:"Tam güneş",     waterDays:2,  care:"Şemsiye şeklinde yapraklar. Çok nemli veya sığ suda yetişir." },
];
